assignments/24-HR-CS2/homework 2/tsiarentsyeu/hw.py
jhlfevrkjhfdvbjhfdvjhdfsvjkhsdfvhkjsdfvjhkdfbqjkh
=> tsiarentsyeu hw 2

assignments/24-HR-CS1/homework 2/isaevi-homework/homework-03-task-1.py, assignments/24-HR-CS1/homework 2/isaevi-homework/homework-03-task-2.py, assignments/24-HR-CS1/homework 2/isaevi-homework/homework-03-task-3.py
=> isaevi-homework-3-done

assignments/24-HR-JA/Seliavko-homework/Seliavko-homework 2.py
=> Create Seliavko-homework 2.py

assignments/24-HR-CS1/homework 2/isaevi-homework/homework-04-tasks-1.py, assignments/24-HR-CS1/homework 2/isaevi-homework/homework-04-tasks-2.py
=> isaevi-homework-04-done

Timofey-Tsvetkov/HW-3/Difficult_Equation.py, Timofey-Tsvetkov/HW-3/Easy_Equation.py, Timofey-Tsvetkov/HW-3/Time.py
=> Give me my lantern

assignments/24-HR-CS1/homework 3/Koptev Egor/Homework3-1.py, assignments/24-HR-CS1/homework 3/Koptev Egor/Homework3-2.py, assignments/24-HR-CS1/homework 3/Koptev Egor/Homework3-3.py
=> HW3 by Egor Koptev

assignments/24-HR-CS1/homework 2/isaevi-homework/homework-5-task-1.py, assignments/24-HR-CS1/homework 2/isaevi-homework/homework-5-task-2.py, assignments/24-HR-CS1/homework 2/isaevi-homework/homework-5-task-3.py
=> isaevi-homework-5-done

assignments/24-HR-JA/Homework 4/Task 1 Seliavko, assignments/24-HR-JA/Homework 4/Task 2 Seliavko
=> Homework 4, Seliavko

assignments/24-HR-JA/Homework 5/Task 1, Seliavko, assignments/24-HR-JA/Homework 5/Task 2, Seliavko, assignments/24-HR-JA/Homework 5/Task 3, Seliavko
=> Homework 5, Seliavko

.idea/highres24.iml, assignments/24-HR-JS/homework 2/shamraeva/homework2.py, materials/Lesson 2 (github flow, data types)/Lesson 2 - basic data types.ipynb
This Python script takes user input for starting amount, annual interest rate, and investment period (in years), then calculates the final investment amount and total profit using compound interest formula.
=> HW2: Python script to calculate investment return from input

assignments/24-HR-JS/homework 3/shamraeva/homework3_task1.py, assignments/24-HR-JS/homework 3/shamraeva/homework3_task2.py, assignments/24-HR-JS/homework 3/shamraeva/homework3_task3.py, materials/Lesson 3 (collections, flow control)/Lesson 3 - collections, flow control.ipynb
Homework 3 (Tasks 1–3):
- Solve quadratic equation (easy)
- Solve quadratic equation (expression parser)
- Time to words conversion
=> Add Homework 3: quadratic equation and time to words

assignments/24-HR-CS1/homework 2/isaevi-homework/hometask-6-task-1.py, assignments/24-HR-CS1/homework 2/isaevi-homework/hometask-6-task-2.py
=> iasevi-homework-6-done

assignments/24-HR-JA/Homework 6/Seliavko homework 6/Seliavko, Task 1, assignments/24-HR-JA/Homework 6/Seliavko homework 6/Seliavko, Task 2
=> Seliavko homework 6

assignments/24-HR-CS2/homework 4/liauchuk_hw4/task1.py, assignments/24-HR-CS2/homework 4/liauchuk_hw4/task2.py, assignments/24-HR-CS2/homework 6/melehov/custom_sort.py, assignments/24-HR-CS2/homework 6/melehov/timer.py
=> Liauchuk hw4

assignments/24-HR-JS/homework 5/pashkovskij/task1.py, assignments/24-HR-JS/homework 5/pashkovskij/task2.py, assignments/24-HR-JS/homework 5/pashkovskij/task3.py
=> do homework 5

assignments/24-HR-CS1/homework 2/isaevi-homework/hometask-7-task-1.py, assignments/24-HR-CS1/homework 2/isaevi-homework/hometask-7-task-2.py
=> isaevi-homework-7-done

assignments/24-HR-JS/homework 6/paskovskij/task1.py, assignments/24-HR-JS/homework 6/paskovskij/task2.py
=> homework 6

assignments/24-HR-CS1/homework 2/Viartsinskaya/hometask4/4.1.py, assignments/24-HR-CS1/homework 2/Viartsinskaya/hometask4/4.2.py, assignments/24-HR-CS1/homework 2/Viartsinskaya/hometask5/5.1.py, assignments/24-HR-CS1/homework 2/Viartsinskaya/hometask5/5.2.py, assignments/24-HR-CS1/homework 2/Viartsinskaya/hometask5/5.3.py, assignments/24-HR-CS1/homework 2/Viartsinskaya/hometask6/6.1.py, assignments/24-HR-CS1/homework 2/Viartsinskaya/hometask6/6.2.py
=> Viartsinskaya hometasks

assignments/24-HR-CS1/homework 2/isaevi-homework/hometask-8.py
ништяковое задание вообще ништяк
=> isaevi-homework-8-done

assignments/24-HR-JS/homework 4/belov/task1.py, assignments/24-HR-JS/homework 4/belov/task2.py, assignments/24-HR-JS/homework 5/belov/task1.py, assignments/24-HR-JS/homework 5/belov/task2.py, assignments/24-HR-JS/homework 5/belov/task3.py, assignments/24-HR-JS/homework 6/belov/task1.py, assignments/24-HR-JS/homework 6/belov/task2.py
Hometasks 4,5,6 Belov Alexander
=> feat: added solution for homework 4,5,6

assignments/24-HR-JA/Seliavko homework 7/Homework 7, Seliavko/Task 1 Seliavko, assignments/24-HR-JA/Seliavko homework 7/Homework 7, Seliavko/Task 2, Seliavko
=> Homework 7, Seliavko

assignments/24-HR-CS2/homework 5/lyskov_hw5/t1.py, assignments/24-HR-CS2/homework 5/lyskov_hw5/t2.py, assignments/24-HR-CS2/homework 5/lyskov_hw5/t3.py
=> lyskov_hw5

assignments/24-HR-CS2/homework 4/lyskov_hw4/task1.py, assignments/24-HR-CS2/homework 4/lyskov_hw4/task2.py
=> lyskov_hw4

assignments/24-HR-CS2/homework 7/lyskov_hw7/t1.py, assignments/24-HR-CS2/homework 7/lyskov_hw7/t2.py
=> lyskov_hw7

assignments/24-HR-JS/homework 7/belov/task1.py, assignments/24-HR-JS/homework 7/belov/task2.py
=> feat: added solution

.idea/highres24.iml, assignments/24-HR-JS/homework 7/shamraeva/combinations_gen.py, assignments/24-HR-JS/homework 7/shamraeva/fib_gen.py, assignments/24-HR-JS/homework 8/calculator.py
Implemented a basic calculator that processes arithmetic expressions with +, -, *, /, without using eval() or re.
User input is handled in a loop with full error handling and informative messages.
This version does not support parentheses or operator precedence.
=> Simple Calculator

assignments/24-HR-CS1/homework 2/Lemesh-homework/homework 8.1.py
=> Create homework 8.1

assignments/24-HR-CS2/homework 7/simanchuk/task-2.py, assignments/24-HR-CS2/homework 7/simanchuk/task1.py, assignments/24-HR-CS2/homework 8/simanchuk/task1.py
=> Simanchuk hw8

assignments/24-HR-JA/homework 8/Seliavko/Task 1
=> Homework 8

assignments/24-HR-JA/homework 9/Homework 9, Seliavko/Task 1
=> Homework 9

assignments/24-HR-JA/Ioda Homeworkks/homework 5.1.py, assignments/24-HR-JA/Ioda Homeworkks/homework 5.2.py, assignments/24-HR-JA/Ioda Homeworkks/homework 5.3.py
=> homework 5

assignments/24-HR-JA/Homework 4/ishchuk-hw4/task1.py, assignments/24-HR-JA/Homework 4/ishchuk-hw4/task2.py
=> ishchuk-hw4
